### ISSUE TITLE
[São Paulo/SP - Híbrido] Desenvolvedor Python - Pleno @ ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [ITeam-oportunidades/VAGAS#5]
> Atendimento Híbrido em São Paulo/SP

## ITeam

Vinte anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

- São Paulo/SP – Chácara Santo Antônio – Híbrido 2 x por semana no escritório das 9h00 as 18h00.

## Requisitos

- Experiência com desenvolvimento em Python e frameworks como Django ou Flask.
- Familiaridade com bancos de dados relacionais e não relacionais.
- Capacidade de fazer integrações e APIs em sistemas legados.

## Imprescindível 

- Python e frameworks como Django ou Flask.
- Base em São Paulo.

## Diferenciais 

- Desenvolvimento web (HTML, CSS, JavaScript); controle de versão e certificações ou cursos relacionados a Python.

## Contratação

- 6 meses com possibilidade de efetivação por parte do cliente. 

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado e pretensão salarial ou de taxa/hora PJ - enviar no assunto: Python Pleno - SP

## Labels

- Python 
- Django
- Flask
- API

## Regime
- PJ 
- CLT

## Nível
- Pleno

**Comment by celsoabreu** [comment]
Tenho interesse em participar deste projeto e tenho experiência para contribuir, analisem meu CV.

**Comment by ITeam-oportunidades** [comment]
Vaga fechada.
